### ISSUE TITLE
Где найти задание?

### ISSUE THREAD

**Issue by Dmitry-Borodin** [FlutterRussia/flutter_ml_workshop_1#1]
Где собственно найти описание 10 шагов, которые надо выполнить?

**Comment by kaparray** [comment]
Привет, простите за долгий ответ)
Вот презентация, в ней всё описано.
https://drive.google.com/open?id=1Rc2i6oAye4MqJXV_Gzw2LzwtnbJVnHEj 

Как начать?
1) Нужно чекаутнутся на 22df48c757ae15338e5ae780277c0a1443505e18 этот кормит
2) Открыть презентацию
3) Кодить :)

Так же посоветовал бы вам:
1) https://dart.dev/guides/language/language-tour (Тур по языку дарт)
2) https://flutter.dev/docs/get-started/flutter-for/android-devs (Статья о том как перейти с Android  на Flutter разработчику)
